doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Cuadrik:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm'
#                type: annotation
#                dir: '%kernel.project_dir%/src/Crm/Domain'
                prefix: 'Cuadrik\Crm\Companies\Domain'
                alias: Cuadrik
