doctrine:
    dbal:
        url: '%env(resolve:APP_DATABASE_DNS)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Companies:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm/companies'
#                type: annotation
#                dir: '%kernel.project_dir%/src/Backoffice/Companies/Domain'
                prefix: 'Cuadrik\Backoffice\Companies\Domain'
                alias: Companies
            Users:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm/users'
#                type: annotation
#                dir: '%kernel.project_dir%/src/Backoffice/Users/Domain'
                prefix: 'Cuadrik\Backoffice\Users\Domain'
                alias: Companies
            Shared:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm/shared'
#                type: annotation
#                dir: '%kernel.project_dir%/src/Backoffice/Shared/Domain'
                prefix: 'Cuadrik\Shared\Domain'
                alias: Shared
