# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Cuadrik\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Cuadrik\Apps\Crm\Api\Controller\:
        resource: '../apps/crm/api/src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # jwt_creation_listener that should complete the token information
    cuadrik.event.jwt_created_listener:
        class: Cuadrik\Crm\Infrastructure\Symfony\EventListener\JWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    Cuadrik\Crm\Infrastructure\Symfony\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onException }

    # add json body in the request data
    Cuadrik\Crm\Infrastructure\Symfony\EventListener\AddJsonBodyToRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Used for tests
    Cuadrik\Crm\Infrastructure\Symfony\Service\JWTDecodeToken:
        public: true




#    user_create_command_handlers:
#        namespace: Cuadrik\Crm\Application\User\
#        resource: '%kernel.project_dir%/src/Crm/Application/User/*Handler.php'
#        autoconfigure: false
#        tags:
#            - { name: messenger.message_handler, bus: command.bus }
#
#    user_login_query_handlers:
#        namespace: Cuadrik\Crm\Application\Security\
#        resource: '%kernel.project_dir%/src/Crm/Application/Security/*Handler.php'
#        autoconfigure: false
#        tags:
#            - { name: messenger.message_handler, bus: query.bus }




#    _instanceof:
#        Cuadrik\Crm\Domain\Shared\Bus\Command\CommandHandler:
#            tags: ['cuadrik.command_handler']
#        Cuadrik\Crm\Domain\Shared\Bus\Query\QueryHandler:
#            tags: ['cuadrik.query_handler']
#        Cuadrik\Crm\Domain\Shared\Bus\Event\DomainEventSubscriber:
#            tags: ['cuadrik.domain_event_subscriber']

#    command_handler:
#        namespace: Cuadrik\Crm\Domain\Shared\Bus\Command\
#        resource: '%kernel.project_dir%/src/Crm/Domain/Shared/Bus/Command/*'
#        autoconfigure: false
#        tags:
#            - { name: messenger.message_handler, bus: command.bus }
#
#    query_handler:
#        namespace: Cuadrik\Crm\Domain\Shared\Bus\Query\
#        resource: '%kernel.project_dir%/src/Crm/Domain/Shared/Bus/Query/*'
#        autoconfigure: false
#        tags:
#            - { name: messenger.message_handler, bus: query.bus }
#
#    event_handler:
#        namespace: Cuadrik\Crm\Domain\Shared\Bus\Event\
#        resource: '%kernel.project_dir%/src/Crm/Domain/Shared/Bus/Event/*'
#        autoconfigure: false
#        tags:
#            - { name: messenger.message_handler, bus: event.bus }

#    Cuadrik\Crm\Domain\Shared\Bus\Command\CommandBus: '@Cuadrik\Crm\Infrastructure\Symfony\Bus\SymfonyCommandBus'
#    Cuadrik\Crm\Domain\Shared\Bus\Query\QueryBus: '@Cuadrik\Crm\Infrastructure\Symfony\Bus\SymfonyQueryBus'
#    Cuadrik\Crm\Domain\Shared\Bus\Event\EventBus: '@Cuadrik\Crm\Infrastructure\Symfony\Bus\SymfonyEventBus'
#
#    Cuadrik\Crm\Infrastructure\Symfony\Bus\SymfonyCommandBus:
#        arguments: [!tagged cuadrik.command_handler]
#        lazy: true
#    Cuadrik\Crm\Infrastructure\Symfony\Bus\SymfonyQueryBus:
#        arguments: [!tagged cuadrik.query_handler]
#        lazy: true
#    Cuadrik\Crm\Infrastructure\Symfony\Bus\SymfonyEventBus:
#        arguments: [!tagged cuadrik.domain_event_subscriber]
#        lazy: true

